
services:
  backend:
    build: ./app/backend
    container_name: proyecto_isi_backend
    ports:
      - "9090:9090"
    networks:
      - pln_net

  frontend:
    build: ./app/frontend
    container_name: proyecto_isi_frontend
    ports:
      - "9390:80"
    depends_on:
      - backend
    networks:
      - pln_net

networks:
  pln_net:
    driver: bridge
