version: "3.9"

services:
  backend:
    build: ./app/backend
    container_name: proyecto_isi_backend
    ports:
      - "9090:80"
    env_file:
      - ./app/backend/.env
    networks:
      - pln_net

  frontend:
    build: ./app/frontend
    container_name: proyecto_isi_frontend
    ports:
      - "9390:80"
    networks:
      - pln_net

networks:
  pln_net:
    external: true
